---
chef:
  endpoint: https://172.18.0.1
  superuser: pivotal
  ssl_verify_mode: verify_none
doorkeeper:
  administrators: []
sign_up_url: https:///signup
email_from_address: '"Opscode" <donotreply@chef.io>'
origin:
